%Try to write one
ColorList=["white","orange","magenta","light_blue","yellow","lime","pink","gray","light_gray","cyan","purple","blue","brown","green","red","black"];

N=GetNBTWriter('D:\游戏\Minecraft\mc相关研究\投影文件的编码格式\WriteXYZ');

N=writeCompound(N,'Metadata');
    N=writeCompound(N,'EnclosingSize');
        N=writeInt(N,'x',2);
        N=writeInt(N,'y',2);
        N=writeInt(N,'z',4);
    N=endCompound(N);
    N=writeString(N,'Author','TokiNobug');
    N=writeString(N,'Description','Generated by -Slope-');
    N=writeString(N,'Name','LorkeMarton');
    N=writeInt(N,'RegionCount',1);
    N=writeLong(N,'TimeCreated',114514);
    N=writeLong(N,'TimeModified',1919810);
    N=writeInt(N,'TotalBlocks',16);
    N=writeInt(N,'TotalVolume',16);

N=endCompound(N);

N.isInList=false;

N=writeCompound(N,'Regions');
    N=writeCompound(N,'X');
        N=writeCompound(N,'Position');
            N=writeInt(N,'x',0);
            N=writeInt(N,'y',0);
            N=writeInt(N,'z',0);
        N=endCompound(N);
        N=writeCompound(N,'Size');
            N=writeInt(N,'x',2);
            N=writeInt(N,'y',2);
            N=writeInt(N,'z',4);
        N=endCompound(N);

        N=writeList(N,'BlockStatePalette',146,10);
            N=writeCompound(N,'');
                N=writeString(N,'Name','minecraft:air');
            N=endCompound(N);
%             N=writeCompound(N,'');
%                 N=writeString(N,'Name','minecraft:glass');
%             N=endCompound(N);
            %写入其他方块列表
            
            for i=1:16
                N=writeCompound(N,'');
                    N=writeString(N,'Name',char(strcat('minecraft:',ColorList(i),'_concrete')));
                N=endCompound(N);                
            end

            N=WriteInTrash(N,129);

        N=endList(N);
        
        N=writeList(N,'Entities',0,10);
        N=endList(N);
        N=writeList(N,'PendingBlockTicks',0,10);
        N=endList(N);
        N=writeList(N,'PendingFluidTiccks',0,10);
        N=endList(N);
        N=writeList(N,'TileEntities',0,10);
        N=endList(N);

        N=writeLongArrayHead(N,'BlockStates',ceil(16/8));
        for i=1:8:16
        N=write8ByteArrayEleReversely(N,i:(i+7));
        end
%         N=writeByteArrayEle(N,0);
        %写入方块状态的long array
    N=endCompound(N);
N=endCompound(N);
N=writeInt(N,'MinecraftDataVersion',2584);
N=writeInt(N,'Version',5);

N=closeNBTWriter(N);
